server:
  net: 1
  cron_spec: "0 0 0 1/1 * *" # refund regular
  hedge_url: "" # call hedge token
db:
  mysql:
    addr: ""
    user: ""
    password: ""
    db_name: ""
    max_open_conn: 100
    max_idle_conn: 100
  parser_mysql:
    addr: ""
    user: ""
    password: ""
    db_name: ""
    max_open_conn: 100
    max_idle_conn: 100
chain:
  ckb:
    refund: true # do refund
    switch: true # start tx parse
    ckb_url: "http://127.0.0.1:8114"
    index_url: "http://127.0.0.1:8116"
    address: "" # receiver's address
    private: "" # private key
    parser_type: 0
    current_block_number: 0
    confirm_num: 4
    concurrency_num: 10
  eth:
    refund: true
    refund_add_fee: 1.1
    switch: true
    node: "http://127.0.0.1:8585"
    address: ""
    private: ""
    parser_type: 1
    current_block_number: 0
    confirm_num: 2
    concurrency_num: 5
  tron:
    refund: true
    switch: true
    node: "127.0.0.1:50051"
    address: ""
    private: ""
    parser_type: 3
    current_block_number: 0
    confirm_num: 10
    concurrency_num: 10
  bsc:
    refund: true
    switch: true
    node: ""
    address: ""
    private: ""
    parser_type: 5
    current_block_number: 0
    confirm_num: 10
    concurrency_num: 10
  polygon:
    refund: true
    switch: true
    node: "https://polygon-rpc.com"
    address: ""
    private: ""
    parser_type: 6
    current_block_number: 0
    confirm_num: 10
    concurrency_num: 10
das_lib:
  thq_code_hash: "0x9e537bf5b8ec044ca3f53355e879f3fd8832217e4a9b41d9994cf0c547241a79"
  das_contract_args: "0xc126635ece567c71c50f7482c5db80603852c306"
  das_contract_code_hash: "0x00000000000000000000000000000000000000000000000000545950455f4944"
  map_das_contract:
    "config-cell-type": "0x3775c65aabe8b79980c4933dd2f4347fa5ef03611cef64328685618aa7535794"
    "account-cell-type": "0x96dc231bbbee6aa474076468640f9e0ad27cf13b1343716a7ce04b116ea18ba8"
    "balance-cell-type": "0xbdc8f42643ccad23e8df3d2e8dbdea9201812cd1b7f84c46e69b020529629822"
    "das-lock": "0xda22fd296682488687a6035b5fc97c269b72d7de128034389bd03041b40309c0"