server:
  net: 1
  cron_spec: "0 0 0 1/1 * *" # refund regular
  hedge_url: "" # call hedge token
db:
  mysql:
    addr: "127.0.0.1:3306" # 172.17.0.1: docker 182.17.0.1: docker-compose
    user: "root"
    password: "123456"
    db_name: "das_register"
    max_open_conn: 100
    max_idle_conn: 100
  parser_mysql:
    addr: "127.0.0.1:3306" # 172.17.0.1: docker 182.17.0.1: docker-compose
    user: "root"
    password: "123456"
    db_name: "das_database"
    max_open_conn: 100
    max_idle_conn: 100
chain:
  ckb:
    refund: true # do refund
    switch: true # start tx parse
    ckb_url: "http://127.0.0.1:8114"
    index_url: "http://127.0.0.1:8116"
    address: "" # receiver's address
    private: "" # private key
    parser_type: 0
    current_block_number: 0
    confirm_num: 4
    concurrency_num: 10
  eth:
    refund: true
    refund_add_fee: 1.1
    switch: true
    node: "http://127.0.0.1:8585"
    address: ""
    private: ""
    parser_type: 1
    current_block_number: 0
    confirm_num: 2
    concurrency_num: 5
  tron:
    refund: true
    switch: true
    node: "127.0.0.1:50051"
    address: ""
    private: ""
    parser_type: 3
    current_block_number: 0
    confirm_num: 10
    concurrency_num: 10
  bsc:
    refund: true
    switch: true
    node: ""
    address: ""
    private: ""
    parser_type: 5
    current_block_number: 0
    confirm_num: 10
    concurrency_num: 10
  polygon:
    refund: true
    switch: true
    node: "https://polygon-rpc.com"
    address: ""
    private: ""
    parser_type: 6
    current_block_number: 0
    confirm_num: 10
    concurrency_num: 10